apiVersion: v1
kind: LimitRange
metadata:
  name: pod-resource-limits
  namespace: default
spec:
  limits:
  - type: Container
    default:
      cpu: 1000m
      memory: 1.75Gi
    defaultRequest:
      cpu: 500m
      memory: 512Mi