apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      # Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      # API Services
      - job_name: 'catalog-api'
        static_configs:
          - targets: ['catalog-api:8080']
        metrics_path: /metrics
        scrape_interval: 10s
      
      - job_name: 'basket-api'
        static_configs:
          - targets: ['basket-api:8080']
        metrics_path: /metrics
        scrape_interval: 10s
      
      - job_name: 'ordering-api'
        static_configs:
          - targets: ['ordering-api:8080']
        metrics_path: /metrics
        scrape_interval: 10s
      
      - job_name: 'webhooks-api'
        static_configs:
          - targets: ['webhooks-api:8080']
        metrics_path: /metrics
        scrape_interval: 10s
      
      - job_name: 'webapp'
        static_configs:
          - targets: ['webapp:8080']
        metrics_path: /metrics
        scrape_interval: 10s
      
      - job_name: 'mobile-bff'
        static_configs:
          - targets: ['mobile-bff:8080']
        metrics_path: /metrics
        scrape_interval: 10s
      
      # Database Services - Using service discovery for better reliability
      - job_name: 'postgres-exporter'
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
              - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: postgres-exporter
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_service_name]
            target_label: job
        metrics_path: /metrics
        scrape_interval: 15s
      
      # Kubelet cAdvisor metrics for container monitoring
      - job_name: 'kubernetes-cadvisor'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        metrics_path: /metrics/cadvisor
        scrape_interval: 10s

      # Kubelet metrics
      - job_name: 'kubernetes-kubelet'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics
        scrape_interval: 10s

      # Kubernetes service discovery for additional services
      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_name